### ISSUE TITLE
Slack Link is broken

### ISSUE THREAD

**Issue by herberthobregon** [gitduckhq/vscode-extension#11]
Slack link in vscode ext is broken

https://gitduck.slack.com/join/shared_invite/zt-ff51epr9-gJvq1G2MC_kAjLuAGeEKMQ#/

Likewise, I do not understand or it is not clear who is sharing the code, if sharing the code is only 1 way or both ways?
How to define who is the one who shares the code?
How delete a Team?

**Comment by drag0s** [comment]
Hey Herberth,

Sorry about the slack link, [this is the correct one](https://join.slack.com/t/gitduck/shared_invite/zt-gf47e9hd-C_~eANAij6WJNKECjzQrUg). We already fixed it on the newer versions!

The first person that clicks on the "Start sharing your files on /..." is the one sharing all the files that he/she opens. The other participants can see and edit that code at the same time but the "source of truth" is on the person that first clicked on that button.

Right now, if you want to change who is sharing the code, you need to "Stop sharing" so the "Start sharing your files on /..." appears again.

We don't have a delete button for teams yet but we can manually delete it for you, just send an email to help@gitduck.com 

Feel free to write if you have more questions or doubts about GitDuck
