### ISSUE TITLE
No extension available

### ISSUE THREAD

**Issue by MarkoShiva** [gitduckhq/vscode-extension#9]
No extension available on marketplce for the VScodium on linux.
That is a OSS version of the vscode compiled from code on github.

**Comment by borisandcrispin** [comment]
Hey Marko, thank you for writing to us.
We don't know when we are going to support VSCodium again. 

The easiest way for now (although not ideal) to use GitDuck with VSCodium is to download and install the vsix file directly from the VSCode Marketplace. https://marketplace.visualstudio.com/items?itemName=gitduck.code-streaming

thank you
